// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDjuqlec_t0GXCGj7NK8bPVV4Q6XVoZq8',
    appId: '1:170378575793:web:d802522e9d16929dde0790',
    messagingSenderId: '170378575793',
    projectId: 'arduino-car7',
    authDomain: 'arduino-car7.firebaseapp.com',
    storageBucket: 'arduino-car7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKHT_6MRibQqkwXeikXwueaB3rmtc_ZZI',
    appId: '1:170378575793:android:5293cd909a784db4de0790',
    messagingSenderId: '170378575793',
    projectId: 'arduino-car7',
    storageBucket: 'arduino-car7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlf4bB3HOuvxhy-zhkGI3f5LO6jeGPT4s',
    appId: '1:170378575793:ios:3790b5d5aaaf40ebde0790',
    messagingSenderId: '170378575793',
    projectId: 'arduino-car7',
    storageBucket: 'arduino-car7.appspot.com',
    iosBundleId: 'com.example.arduinoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlf4bB3HOuvxhy-zhkGI3f5LO6jeGPT4s',
    appId: '1:170378575793:ios:28020d03cdbc3ebede0790',
    messagingSenderId: '170378575793',
    projectId: 'arduino-car7',
    storageBucket: 'arduino-car7.appspot.com',
    iosBundleId: 'com.example.arduinoApp.RunnerTests',
  );
}
